name: gestion_clientes_carniceria
description: Aplicación de gestión de clientes.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.0
  intl: ^0.20.2
  google_nav_bar: ^5.0.7
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  pdf: ^3.11.3
  printing: 5.13.1
  share_plus: 9.0.0
  path_provider: ^2.1.5
  curved_navigation_bar: ^1.0.6
  lucide_icons: ^0.257.0
  image_picker: ^1.2.0
  shared_preferences: ^2.5.3
  flutter_slidable: ^4.0.3
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
