// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptionsDev.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsDev have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsDev are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDveZv2CZdDqw-rx91M9suc0GeBKjUhn8',
    appId: '1:169345996032:web:7bab839b6be7cfd1e6cfe5',
    messagingSenderId: '169345996032',
    projectId: 'mispaggosdev',
    authDomain: 'mispaggosdev.firebaseapp.com',
    storageBucket: 'mispaggosdev.firebasestorage.app',
    measurementId: 'G-DJC0XW2SEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbGx1y4CAv1WN7fFWYY6UloUgl8VA5on0',
    appId: '1:169345996032:android:ab1f518e50bbe93fe6cfe5',
    messagingSenderId: '169345996032',
    projectId: 'mispaggosdev',
    storageBucket: 'mispaggosdev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKb_8jKN1RJWD6i0DRPeqjAzLyE2r49k0',
    appId: '1:169345996032:ios:a5af61004e4db2bfe6cfe5',
    messagingSenderId: '169345996032',
    projectId: 'mispaggosdev',
    storageBucket: 'mispaggosdev.firebasestorage.app',
    iosBundleId: 'com.example.gestionClientesCarniceria',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKb_8jKN1RJWD6i0DRPeqjAzLyE2r49k0',
    appId: '1:169345996032:ios:a5af61004e4db2bfe6cfe5',
    messagingSenderId: '169345996032',
    projectId: 'mispaggosdev',
    storageBucket: 'mispaggosdev.firebasestorage.app',
    iosBundleId: 'com.example.gestionClientesCarniceria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDveZv2CZdDqw-rx91M9suc0GeBKjUhn8',
    appId: '1:169345996032:web:ae993dc424f11606e6cfe5',
    messagingSenderId: '169345996032',
    projectId: 'mispaggosdev',
    authDomain: 'mispaggosdev.firebaseapp.com',
    storageBucket: 'mispaggosdev.firebasestorage.app',
    measurementId: 'G-NE8E7W290D',
  );
}
