// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5gPqGZBjwfM8C2I7KXDdqKhVtEGtXl5U',
    appId: '1:541520544710:web:b1f6c0e2b61f194b4728c7',
    messagingSenderId: '541520544710',
    projectId: 'systdm-ef45c',
    authDomain: 'systdm-ef45c.firebaseapp.com',
    storageBucket: 'systdm-ef45c.firebasestorage.app',
    measurementId: 'G-G2VEGV86EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuPYzMogtKg9MLoOcMafogf3wBS-60PyI',
    appId: '1:541520544710:android:2ea79b89169a605a4728c7',
    messagingSenderId: '541520544710',
    projectId: 'systdm-ef45c',
    storageBucket: 'systdm-ef45c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6T-wkT_uo8E8r4tNKkjtj3YUjfCDJxb8',
    appId: '1:541520544710:ios:89cc380de078950a4728c7',
    messagingSenderId: '541520544710',
    projectId: 'systdm-ef45c',
    storageBucket: 'systdm-ef45c.firebasestorage.app',
    iosBundleId: 'com.example.gestionClientesCarniceria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6T-wkT_uo8E8r4tNKkjtj3YUjfCDJxb8',
    appId: '1:541520544710:ios:89cc380de078950a4728c7',
    messagingSenderId: '541520544710',
    projectId: 'systdm-ef45c',
    storageBucket: 'systdm-ef45c.firebasestorage.app',
    iosBundleId: 'com.example.gestionClientesCarniceria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5gPqGZBjwfM8C2I7KXDdqKhVtEGtXl5U',
    appId: '1:541520544710:web:0ad1241af6a044f24728c7',
    messagingSenderId: '541520544710',
    projectId: 'systdm-ef45c',
    authDomain: 'systdm-ef45c.firebaseapp.com',
    storageBucket: 'systdm-ef45c.firebasestorage.app',
    measurementId: 'G-YPE5K5WNHD',
  );
}
